### ISSUE TITLE
Please give me some suggestion

### ISSUE THREAD

**Issue by Chococobee** [worldveil/dejavu#106]
Hi I'm a student and I'm new at Python Language.I'm interested in this project and I don't How it work after fingerprinting the audio. Can you suggest me some How It work  and testing code? Thank you for suggestion

**Comment by worldveil** [comment]
Go through the README, you'll find examples there.

**Comment by yeboahnanaosei** [comment]
Hi, @Chococobee if you want dejavu to listen and identify a song try these steps:
* Open your terminal and navigate to the dejavu directory.
* Once inside the dejavu directory type:  **`python dejavu.py -r mic 5`**
    > `python dejavu.py` will start the program.
    > `-r` specifies the action for dejavu to perform. In this case `-r` means _recognize_. You are telling dejavu to listen and identify an audio.
    > `mic` specifies the source of the audio.
    > `5` specifies the number of seconds dejavu should listen to the audio. _You can set this to a value of your choice_
* Play a song into the microphone of your machine. _**NB: The song you play should be a song that you have already fingerprinted and stored in the database.**_
* After some seconds, dejavu should output the song or audio file it recognized.

I hope this helps you.
