### ISSUE TITLE
Can dejavu be used to match songs by different singers? 

### ISSUE THREAD

**Issue by ahmedk92** [worldveil/dejavu#111]
I mean, instead of testing with a playback; can I test with my own voice? (we can assume no music included)

**Comment by algeorge** [comment]
yes but it has to be a music wave not only vocal

**Comment by worldveil** [comment]
No. 

From the README:

> Note that for voice recognition, Dejavu is not the right tool! Dejavu excels at recognition of exact signals with reasonable amounts of noise.
