### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by jinfagang** [worldveil/dejavu#114]
Did this work support MongoDB? I think mongo is more convenient to store those fingerprints (most of my project were using Mongo), so just want to sure if dejavu support mongo, if it does, how to config in dejavu?

**Comment by algeorge** [comment]
its possible i think, i will  try implement it on this project...

**Comment by jinfagang** [comment]
@algeorge That would be nice! Another question, can this repo using for recognize different human voice? For example to differ my voice and my friends?

**Comment by algeorge** [comment]
No its only for audio noise see:
 "Note that for voice recognition, Dejavu is not the right tool! Dejavu excels at recognition of exact signals with reasonable amounts of noise." if you are looking for voice recog then theres alot of repo can do that.

**Comment by jinfagang** [comment]
Thanks pal, I am newbie in voice recognition, do know any opensource tools which can using for train a model to recognize voice or convert voice into text?

**Comment by algeorge** [comment]
theres few of them but i like Pocketsphinx  i used mainly for my talking chatbot. "google is the magic!!!"

**Comment by worldveil** [comment]
@jinfagang no Mongo support at this time. 

@jinfagang @algeorge there are many tools to do ASR (speech to text). Google, MS, IBM all have their own offerings.
