### ISSUE TITLE
Heroku - MySQLdb not suported on heroku

### ISSUE THREAD

**Issue by v2lrf** [worldveil/dejavu#116]
Hi 
=> I m investigating how push Dejavu on heroku but I know that MySQL is not supported on. i founded some Addons, Heroku devcenter seams to advice dev to use ClearDB  addon  (here the link https://goo.gl/ig9ary) however the problem persist and i m stuck since 4 days ^-^ and i have this message error 
=> “import MySQLdb as mysql / ImportError: No module named MySQLdb”. It is not a surprise because MySQLdb is not installed on my heroku instance.”
=> how to import within a normal syntax MySQLdb through any kind of addon? 

Do you have any kind of advices about that problem, i often use Heroku but i wonder to know if it would be easier to use an other deployment service? like AWS or  other one. Finaly if it s possible to use Heroku it’s perfect but for now, it’s impossible to me to figure how to fix it.

**Comment by rosariopfernandes** [comment]
Hi, I'm also looking to deploy it to Heroku. Can you tell me if you were able to install all the other dependencies (pyaudio, numpy, etc)? If yes, how to do it?

**Comment by viny212** [comment]
not done yet :-/

**Comment by HassanAzam** [comment]
Hey @HHGB12 , Did you find the solution ?

**Comment by worldveil** [comment]
Postgres is now supported.
