### ISSUE TITLE
Not working on OS X Sierra

### ISSUE THREAD

**Issue by alejandrojapkin** [worldveil/dejavu#127]
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from dejavu import Dejavu
  File "dejavu/dejavu/__init__.py", line 1, in <module>
    from dejavu.database import get_database, Database
  File "dejavu/dejavu/database.py", line 176, in <module>
    import dejavu.database_sql
  File "dejavu/dejavu/database_sql.py", line 5, in <module>
    import MySQLdb as mysql
ImportError: No module named MySQLdb

Tried various Mysql versions, settings, Python distributions and virtualenvs. None works. Did the dylib linking by bypassing rootless mode (FYI, OS X can't ln -s system files for a while now). This problem seems similar to the problems people are having with Heroku and other distributions.

**Comment by nishathussain** [comment]
sys.path.insert(0,'/Library/Python/2.7/site-packages')
import MySQLdb

**Comment by datascienceteam01** [comment]
Not working with
from multiprocessing import Queue
import MySQLdb as mysql
sys.path.insert(0,'/virtualenv/lib/python3.6/site-packages')
from MySQLdb.cursors import DictCursor

ImportError: dynamic module does not define module export function (PyInit__mysql)

**Comment by datascienceteam01** [comment]
Same error with python 2.7 but:

ImportError: dynamic module does not define init function (init_mysql)
