### ISSUE TITLE
How to know the accuracy of the result ?

### ISSUE THREAD

**Issue by monyoudom** [worldveil/dejavu#130]
I wonder. When I try to recognize the song that not exit my database. It give me the wrong result. I feel it random choose.

**Comment by anuragkumarak95** [comment]
this module will produce the most nearest neighbor to the song you input. What you need to do is provide a threshold to the final confidence value to only return a match if confidence is considerable.

**Comment by gitteraz** [comment]
How do i use the "relative_confidence" value to decide if the returned song was the correct one?

**Comment by mauriciorepetto** [comment]
As @JPery did, I have also added a pr with actually two confidences: https://github.com/worldveil/dejavu/pull/205 one that checks matches against the hashes in the db and other that measures hashes matched from the song.. depending on your problem you can use one or the other. Still is not a perfect confidence measure but at least is something.
