### ISSUE TITLE
Can you use the LSH algorithm to compute distance between tracks?

### ISSUE THREAD

**Issue by jrjames83** [worldveil/dejavu#133]
Can you convert the hashing output to some kind of vector which can be used to compute distance between tracks (eg, Track A sounds like Track Z, but sounds nothing like Track D?). 

Or does the hashing algorithm mainly excel at identifying the same track?

Thanks, 

Jeff

**Comment by VladLimbean** [comment]
I am also quite curious for a response on this matter.

**Comment by worldveil** [comment]
Not really. Unfortunately the hashes generated by this particular LSH algorithm are very local - they don't have much meaning outside the context of other, nearby hashes in time.
