### ISSUE TITLE
recognize fails but example.py and run_tests.py succeeds

### ISSUE THREAD

**Issue by sharkmerry7** [worldveil/dejavu#144]
Im not quite sure what I am doing wrong. All audio has been fingerprinted. 

If I run dejavu.py with "recognize" option, it returns None. If i set the example.py to the same file, it returns properly. Run_tests.py has similar results. 

What am I doing incorrectly?

(dejavu_env) msherry@mark-desktop:~/dejavu_env/dejavu$ python dejavu.py --recognize arid.mp3 ./testfiles/
None
(dejavu_env) msherry@mark-desktop:~/dejavu_env/dejavu$ python dejavu.py --recognize arid.mp3 ./testfiles
None
(dejavu_env) msherry@mark-desktop:~/dejavu_env/dejavu$ python example.py 
From file we recognized: {'song_id': 5, 'song_name': 'arid', 'file_sha1': 'D99FB7DB2CCBF717301D584485B324D1F478410D', 'confidence': 4290, 'offset_seconds': 0.0, 'match_time': 4.677971124649048, 'offset': 0}

(dejavu_env) msherry@mark-desktop:~/dejavu_env/dejavu$ cat example.py 
import warnings
import json
warnings.filterwarnings("ignore")

from dejavu import Dejavu
from dejavu.recognize import FileRecognizer, MicrophoneRecognizer

# load config from a JSON file (or anything outputting a python dictionary)
with open("dejavu.cnf.SAMPLE") as f:
    config = json.load(f)

if __name__ == '__main__':

    # create a Dejavu instance
    djv = Dejavu(config)

    # Fingerprint all the mp3's in the directory we give it
#    djv.fingerprint_directory("mp3", [".mp3"])

    # Recognize audio from a file
    song = djv.recognize(FileRecognizer, "testfiles/arid.mp3")
    print "From file we recognized: %s\n" % song

Thanks!!!
-Mark

**Comment by sharkmerry7** [comment]
Im dumb. Closing

**Comment by King-Del-ErnestO** [comment]
i don't understand how this was solved. Can you help please
