### ISSUE TITLE
doesn't work with windows 10 running python 3.6

### ISSUE THREAD

**Issue by louidji02** [worldveil/dejavu#151]
When i want to run exemple.py, i get an error on database_sql.py while importing MySQLdb
"ModuleNotFounderror: No module named 'MySQLdb'"

**Comment by detectivebag** [comment]
for py3, I use mysqlclient-1.3.12 instead, it works for me. seems current project is not compatible with py3, and from https://github.com/worldveil/dejavu/pulls there have been some efforts transforming into py3 compatible. I also make a [py3 version](https://github.com/detectivebag/dejavu) one. hope this helps.

**Comment by mauriciorepetto** [comment]
Hi, I've just created a new and fresh version to support python 3.6.6 with a newer mysql connector and also I've added support for postgresql. You can check it here: https://github.com/worldveil/dejavu/pull/205

**Comment by worldveil** [comment]
Unfortunately, I never truly did any work to support MS windows.
