### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by pk97** [worldveil/dejavu#157]
Cannot install FFmpeg and Mysqldb packages in Linux environment 
command as given in INSTALLATION.md  :
sudo yum install numpy scipy python-matplotlib ffmpeg portaudio-devel

not working on ubuntu as "yum:command not found"

So I replaced "yum" by pip and got the following error :  

install: target 'portaudio-devel' is not a directory
So i manuaaly created a folder "portaudio-devel" and ran the command again. Following error came up->
 Could not find a version that satisfies the requirement python-matplotlib (from versions: )
No matching distribution found for python-matplotlib

**Comment by pk97** [comment]
[ffmpy](https://pypi.org/project/ffmpy/) is this equivalent for ffmpeg?

**Comment by lordkyzr** [comment]
You could try. It looks like from their docs it compiles ffmpeg from source
and is just a python wrapper for the CLI. As long as it copies it to
somewhere on your path I don't see why it wouldn't work. Was there an issue
installing the ffmpeg libraries from their deb package?
