### ISSUE TITLE
Has anybody created a fork?

### ISSUE THREAD

**Issue by yeboahnanaosei** [worldveil/dejavu#160]
It appears that the original maintainer of this project is no longer working on this project however the project still seems to have a lot interest. If anyone has created a fork, kindly give us the link to it so we can pull in the latest improvements.

**Comment by bcollazo** [comment]
Was just looking for this. Glancing at http://forked.yannick.io/worldveil/dejavu I couldn't find one with significant more work; just DataWookie's and MarketTrack's which mainly add Python 3 support.

I just created one https://github.com/bcollazo/dejavu and updated README with the goals.  It already has the main bug fix, such that you can `pip install git+https://github.com/bcollazo/dejavu.git#egg=PyDejavu` in your project and it should work.

**Comment by mauriciorepetto** [comment]
just in case... I've a new and fresh pr for dejavu on 3.6.6 with mysql and postgresql working here https://github.com/worldveil/dejavu/pull/205
