### ISSUE TITLE
Golang alternative to dejavu

### ISSUE THREAD

**Issue by noodlecak-e** [worldveil/dejavu#163]
Can someone help me find a golang alternative to this library? I've scoured the internet and I've come up with nothing. Maybe you could help me search. Or let's write a golang library based on dejavu ourselves.

**Comment by loretoparisi** [comment]
I'm not aware of any alternative to `dejavu` actually, that has the same design, implementation, etc. like commercial products. Maybe it's possible to think to some wrappers of `dejavu` api to other languages.

**Comment by CwbhX** [comment]
Not that I mess with Go much, but have a look into chromaprint. I think they might have a wrapper for Go. Will's project is so unique since it's really easy to understand and grasp imo

**Comment by ItsFunny** [comment]
have u found the alternative util ?

**Comment by worldveil** [comment]
A golang port would be very cool! I don't quite have the time and effort for it (I am already absent enough in my own repo), but please feel free to make use of the code & ideas here.
