### ISSUE TITLE
Can you recognize a person using dejavu?

### ISSUE THREAD

**Issue by MadhavVij** [worldveil/dejavu#165]
My problem is to identify different people and recognizing their voice. Can I use this library and tweak things up to recognizing them (even if they say different things)?

**Comment by JPery** [comment]
I suppose the problem that you have is Speaker diarisation and Dejavu is not intended to do so. This library detects the "exact" audio signal.

**Comment by MadhavVij** [comment]
Thanks a lot for your response.

**Comment by MadhavChoudhary** [comment]
That would be a new project idea. And a nice one.

**Comment by awemulya** [comment]
I have tried speech recognition with this library and i got lot of noises, false detection.
works perfectly for Music.

**Comment by worldveil** [comment]
This library is not meant for that purpose - please read the README. Thanks!
