### ISSUE TITLE
why does the same song when recognizing return negative offset_seconds 

### ISSUE THREAD

**Issue by alic-xc** [worldveil/dejavu#168]
when i fingerprint a song (wav format) and i try to recongise it the offset second return a negative value. is there a need to change the config in the fingerprint.py to get a correct value ?

**Comment by worldveil** [comment]
Can you give an example file & code to reproduce this?

**Comment by alvis-do** [comment]
I founded an example of a negative offset_second value in the README.md of this project. 
`{'total_time': 2.863781690597534, 'fingerprint_time': 2.4306554794311523, 'query_time': 0.4067542552947998, 'align_time': 0.007731199264526367, 'results': [{'song_id': 1, 'song_name': 'Taylor Swift - Shake It Off', 'input_total_hashes': 76168, 'fingerprinted_hashes_in_db': 4919, 'hashes_matched_in_input': 794, 'input_confidence': 0.01, 'fingerprinted_confidence': 0.16, 'offset': -924, 'offset_seconds': -30.00018, 'file_sha1': b'3DC269DF7B8DB9B30D2604DA80783155912593E8'}, {...}, ...]}`
Does this value valid?
