### ISSUE TITLE
Dejavu in JAVA

### ISSUE THREAD

**Issue by csetanmayjain** [worldveil/dejavu#183]
Hello,
Anyone try to implement dejavu in java?
Thanks

**Comment by JPery** [comment]
I think you're looking for something similar to (this)[https://github.com/hsyecheng/Audio-Fingerprinting]. That project has been unchanged for 4 years so I've created a fork in which I've added some improvements, you can see it [here](https://github.com/JPery/Audio-Fingerprinting)

**Comment by endyleon** [comment]
Hi, @JPery. Are the fingerprints generated with the java code the same as those of Dejavu? That is, can I use the java code for an android app and dejavu for the backend?

**Comment by JPery** [comment]
Hi, @endyleon. As these are different projects with different algorithms, the generated fingerprints will not be compatible. Although you can check out the java project as it already provides a client-server approximation that could be useful for your application.

Hope this helps!

**Comment by worldveil** [comment]
Please feel free to port this elsewhere to Java or anywhere else! Happy to see the algorithm & ideas be used as widely and accessibly as possible.
