### ISSUE TITLE
Song recognition from file recorded with smartphone

### ISSUE THREAD

**Issue by caveandre** [worldveil/dejavu#184]
Hey! Dejavu Is great, but i'm facing problems when I try to recognise songs with audio files recorded with smartphone.

Dejavu find a Song but it's never the right Song, so Is there a way to stream audio data from android to dejavu so I can use micRecognition? (I'm developing a phonegap app) Thank so much!

**Comment by 9nehS** [comment]
What about making Dejavu as WEB API and then post your recorded audio to that API for recognition?

**Comment by caveandre** [comment]
The problem is that using the recorded file with the smartphone will not give me the right result because the fingerprinted song come from an MP3 file that is "pure" with no background noise or other interferences. I'd like ti use the microphone recognition also with a recorded file, or an audio stream from the smartphone, but I don't know how to adapt the script

**Comment by 9nehS** [comment]
I've used Dejavu to recognize audio chime for vehicles, just fingerprinted the original .wav audio chime files, and then use my Laptop to record the played audio chime from test bed. After that, posted the recorded .wav file to Dejavu WEB API and get the recognition result.

**Comment by caveandre** [comment]
Yes, with PC All work well but I have ti use the smartphone to record and not PC or laptop :( any ideas?
Thank you!

**Comment by 9nehS** [comment]
Not sure if changing the format for recorded audio can help (e.g. from .mp3 to .wav).

**Comment by lordkyzr** [comment]
It absolutely makes a difference. With all of my testing the wav files did
not work with MP3 recognized files. I am pretty sure they all have to be
the same codec. The second I did WAV to WAV or MP3 to MP3 it worked.

**Comment by caveandre** [comment]
You are two Genius! Changing the format was the clue! In my db i have fingerprinted MP3 songs so I changed the recorded Song format from WAV to MP3 and all works! Thanks a lot guys!

**Comment by lordkyzr** [comment]
Glad it was a simple fix and it's working for you! Happy coding!
