### ISSUE TITLE
SyntaxError: invalid syntax test_dejavu.sh

### ISSUE THREAD

**Issue by Krackle** [worldveil/dejavu#195]
How would one change the test_dejavu.sh to be current, please?
I am sorry if this is a simple task I am still learning. Thanks

    SyntaxError: invalid syntax
    (base) Krackle-MBP-2:Dejavu krackle$ python3 test_dejavu.sh 
    File "test_dejavu.sh", line 18
    python run_tests.py \

**Comment by gorgobacka** [comment]
The file "test_dejavu.sh" is not a Python script. Therefore, you can't use it with `python3 ...`.

You have to run it like: `sh test_dejavu.sh ` or alternatively `./test_dejavu.sh`, if it is already executable.

**Comment by Krackle** [comment]
Thank you. I have been struggling with the database part of dejavu I only want to play with a few test files. Pymysql and mysql with brew do not seem able to play nice. Thanks again.
