### ISSUE TITLE
How to change frequency bins in specgram to improve recall rate?

### ISSUE THREAD

**Issue by thesby** [worldveil/dejavu#200]
I find that bins of frequency of specgram is exactly `NFFT/2 + 1`.  But how can change the bins of frequency, and not change the NFFT ? NFFT affects how many sample to use in FFT. But why does it also affect bins of frequency?

**Comment by worldveil** [comment]
https://electronics.stackexchange.com/questions/12407/what-is-the-relation-between-fft-length-and-frequency-resolution
