### ISSUE TITLE
only run on python2.7?

### ISSUE THREAD

**Issue by shazhongcheng** [worldveil/dejavu#201]
i want to run it on python3 ,  but it doesn`t work. i try to fix to error,but failed QAQ

i don`t want to run it on python2.7. can any body help me to fix it and i can run it on pthon3 fluently!

thank anyone!

**Comment by mmutiso** [comment]
I am running through the same problem. We might have to fork and update

**Comment by yeboahnanaosei** [comment]
You might be looking for this https://github.com/worldveil/dejavu/issues/160#issuecomment-402599796

**Comment by shazhongcheng** [comment]
> You might be looking for this [#160 (comment)](https://github.com/worldveil/dejavu/issues/160#issuecomment-402599796)

thank you!

**Comment by mauriciorepetto** [comment]
hello guys! I've opened a new pull request here https://github.com/worldveil/dejavu/pull/205 I added support for python 3.6.6 and the solution is also available for postgresql

**Comment by Coltin-dev** [comment]
> hello guys! I've opened a new pull request here #205 I added support for python 3.6.6 and the solution is also available for postgresql

Hey mauriciorepetto,

I'm getting an error trying to install pyAudio when using python3. Did you run into this issue?

Thanks!
