### ISSUE TITLE
identify songs by hash to not re-fingerprint files?

### ISSUE THREAD

**Issue by pguridi** [worldveil/dejavu#21]
does it make sense instead of checking by the filename (which is not reliable.. because the files may be moved, or renamed..), use some kind of hash without the metadata?.

ie: would this [1] work?. I think It would, but only for mp3s.., what about other formats?.

[1] https://github.com/sptim/mp3hash

**Comment by thesunlover** [comment]
Let's weigh the options..

if we add the feature we will:
+ dont refingerprint same songs
+ we shall not need to lookup for the same hashes in the DB during recognition
- we will have to do additional CPU job, but it will only depend on how often do we add new songs.
