### ISSUE TITLE
Is dejavu good for similar music track finding?

### ISSUE THREAD

**Issue by nebulaf91** [worldveil/dejavu#219]
If I compare the fingerprints of two similar songs(eg, from the same singer, or they listened quite similar), are the fingerprints similar？

**Comment by outhud** [comment]
Dejavu won't find similar songs as you describe. The features it looks for to generate the fingerprints do not identify singer, genre or anything like this.

It checks whether or not the frequency domain spectrum analyses have similar features (as I understand).

**Comment by worldveil** [comment]
Not really. Dejavu is for finding audio, plus or minus noise. Stretching or otherwise "similar" recordings aren't what it was built for.
