### ISSUE TITLE
Drastically different results with mic recognition

### ISSUE THREAD

**Issue by MrDrWaffle** [worldveil/dejavu#229]
When cutting out a snippet from the original mp3 file, it recognizes it perfectly, confidence levels usually not below 500. But when I try to have it recognize by mic, or recognize a file recorded by mic, it recognizes it totally inaccurately with confidence levels never above 10. I am on Ubuntu 18.04 and am using pavucontrol to record audio from the monitor of system audio. The recorded clips I used were 10 seconds long.

**Comment by nickolaspz** [comment]
Yeah, sounds very similar to #222 .
Still haven't figured it out :(

**Comment by worldveil** [comment]
Well, your mic could be introducing more noise, perhaps too much to recognize the audio?
