### ISSUE TITLE
fingerprint py explain

### ISSUE THREAD

**Issue by katumping** [worldveil/dejavu#230]
hi sir,

sorry i'm new comer for python, but i really need to explain.

could you please explain or give me example separate:
https://github.com/worldveil/dejavu/blob/master/dejavu/fingerprint.py

in this code:
  struct = generate_binary_structure(2, 1)

if right, the function is generate from spectogram get number binary, and will be save to database, I try find google but can't convert to text file when I running def function. it means I copy only def with import the library, but still not convert. always error.

please help, gimme example how to convert to text with mp3 file. so i can clear understand, how the scipy, and numpy able to convert to text

sorry if my english not polite, i try my best to explain what I still confuse of your script.

thank you

**Comment by worldveil** [comment]
That's likely part of the code we use to find the maximums in the spectrogram.
