### ISSUE TITLE
can not fingerprint the mp3 files in the directionary mp3.

### ISSUE THREAD

**Issue by dianaxun** [worldveil/dejavu#231]
hello,
i use python2.7 under ubuntu 18.04,i ran the example.py,it raises errors:No such file or directory.
i debug it ,and find `djv.fingerprint_directory("mp3", [".mp3"])`,i dig in,and finally find that it went wrong after the process of function imap_unordered.though i get there,i don not know where it exactly wrong and how to fix it.have anyone ever come across this problem or fix it.

**Comment by worldveil** [comment]
You need to give a script reproducing this for anyone here to help you.
