### ISSUE TITLE
Meaning of output (Diff and Offset)

### ISSUE THREAD

**Issue by edwinmugendi** [worldveil/dejavu#27]
I have pulled Dejavu and fingerprinted a file.

What does the Diff and offset in this output mean?

"Diff is -25999 with 2 offset-aligned matches"

Thanks

**Comment by wangzhengyi** [comment]
offset_seconds means the match begin time? anybody who can tell me how to get the match begin time??

**Comment by worldveil** [comment]
Yes, `offset_seconds` is the number of seconds before the recognized clip starts.
