### ISSUE TITLE
does it suport no database?

### ISSUE THREAD

**Issue by haha010508** [worldveil/dejavu#275]
i have no database, and i have about only 500 songs, so if i do not use the database such as mysql or others, how i to modify the code?

**Comment by busterbeam** [comment]
I don't think so.  the "crucial" code to fingerprinting and the rest is in [fingerprint.py](https://github.com/worldveil/dejavu/blob/master/dejavu/logic/fingerprint.py).  If you want to setup your own system from scratch work out from that script.  the scripts connected to this one deal with encoding and decoding audio and the ones connected with those handle input and output e.g. microphone, terminal and database.

**Comment by haha010508** [comment]
thanks for your reply, i will try, and i want to know if have some tools to replace the mysql, faiss is ok?

**Comment by haha010508** [comment]
i install mysql in dockerfile
