### ISSUE TITLE
figerprinting file

### ISSUE THREAD

**Issue by 5thmoon** [worldveil/dejavu#297]
The fingerprint directory works just fine but when trying to run the fingerprint_file(), it keeps returning a type error for unexpected keyword argument.  Passed it the path to the file and the filename and tried many variations of arguments but always the same error.  Has anyone run into the same problem?

song_name, hashes, file_hash = Dejavu._fingerprint_worker(
TypeError: Dejavu._fingerprint_worker() got an unexpected keyword argument 'song_name'

**Comment by Bloos** [comment]
bug is still present on master branch
