### ISSUE TITLE
Recognizing issue with Ubuntu 14.04 via microphone

### ISSUE THREAD

**Issue by joei4cm** [worldveil/dejavu#53]
I'm appreciate for you great code in audio fingerprint analyzing, but I have met some issue during microphone recognizing.
My sound cards setup is:
cat /proc/asound/cards 
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7c34000 irq 49
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7c30000 irq 50

And when I am trying to recognizing the music via mic, error occurs:
python dejavu.py recognize mic 20
<b>logged here</b>
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

Could you pls. help me to find out anything missing? Thanks.

**Comment by pywrangler** [comment]
i am having the same problem...did you find a fix?

**Comment by Vinalti** [comment]
I have the same problem.
Did someone find a solution ?
There is the details  : 
- This problem occurs on my 2 OS on the same computer : Ubuntu 14.04 and Kali Linux
- The sound works properly with YouTube
- Micro is activated and works in the parameters 
- The error message is this one : 

> ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> bt_audio_service_open: connect() failed: Connection refused (111)
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave

Thank you

**Comment by mvrozanti** [comment]
Same problem.

```
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
```

I do have a setup where I pipe my default speaker into my mic. Maybe I should disable it..?
