### ISSUE TITLE
Multiple fragments from one mp3 file

### ISSUE THREAD

**Issue by henkit** [worldveil/dejavu#66]
Hi,

I've been playing around with deja vu and able to recognize one fingerprinted fragment but what i would like is to recognize all the known audio fragments from one 10 min audio file. I've been reading trough the issues but not able to find similar questions or examples. Can anyone please help me out with this? I must also say that i'm a newbie to python :)

Cheers,
Henk

**Comment by henkit** [comment]
Hi,

Thanks for you response, more then happy to. I'm using this to fingerprint the commercials:

```
from dejavu import Dejavu
import warnings
import json
warnings.filterwarnings("ignore")

# load config from a JSON file (or anything outputting a python dictionary)
with open("commercial.cnf") as f:

    config = json.load(f)

# create a Dejavu instance
djv = Dejavu(config)

# Fingerprint all the mp3's in the directory we give it
djv.fingerprint_directory("../commercials/december", [".wav"])
```

And I use this piece of code to scan trough a directory containing all the parts (currently 20 sec parts) of a larger recording I did split using ffmpeg.:

```
from dejavu import Dejavu
from dejavu.recognize import FileRecognizer
import os, fnmatch

def find_files(directory, pattern):
    for root, dirs, files in os.walk(directory):
        for basename in files:
            if fnmatch.fnmatch(basename, pattern):
                filename = os.path.join(root, basename)
                yield filename

config = {
    "database": {
         "host": "---",
       	"user": "---",
       	"passwd": "---", 
       	"db": "---"
     },
     "database_type" : "mysql",
}

# create a dejavu object
djv = Dejavu(config)

# gather files to fingerprint
UNLABELED_AUDIO_DIR = "../test/"
PATTERN = "*.wav"
audio_paths = find_files(UNLABELED_AUDIO_DIR, PATTERN)

# recognize them one at a time
original_file_to_song = {}
for path in audio_paths:
    print "Attempting to recognize %s..." % path
    song = djv.recognize(FileRecognizer, path)
    original_file_to_song[path] = song

#print "Audio file at: %s was recognized as %s" % (path, song)
# see the songs you've recognized
for path, song in original_file_to_song.iteritems():
    print "Audio file at: %s was recognized as %s" % (path, song)
```

I also created a zip of the files i'm testing on, you can download it here: www.henk.it/deja_vu/examples.zip (246MB). For example:

- 20141229-0957-_00-00.wav > Should give _no_ match
- 20141229-0957-_00-01.wav > Should give _no_ match
- 20141229-0957-_00-02.wav > Should give _no_ match
- 20141229-0957-_01-00.wav > Could give a match in the last few seconds
- 20141229-0957-_01-01.wav > Should  __match__ with 20141229-0957-dezorg_veranderd_mee commercial

Hope this helps, please let me know if you need additional information.

Cheers,
Henk

**Comment by henkit** [comment]
Hi,

Any chance you where able to look why I do get matches when it shouldn't?

Cheers,
Henk


Verstuurd vanaf mijn iPad

**Comment by henkit** [comment]
Hi worldveil,

You perhaps have an update for me? Don't get it why I do get a match on fragments when I should not return a match.

Cheers,
Henk

**Comment by 454832707** [comment]
> Hi worldveil,
> 
> You perhaps have an update for me? Don't get it why I do get a match on fragments when I should not return a match.
> 
> Cheers,
> Henk

I have same situation as finding multiple fragments from one file. Is there any code that I can learn?
Thanks henkit
