### ISSUE TITLE
decoding failed

### ISSUE THREAD

**Issue by halobalazs** [worldveil/dejavu#68]
Hello!

When I want to make the fingerprints, I get the following error:
![image](https://cloud.githubusercontent.com/assets/5587935/5975348/f794b564-a87f-11e4-80c7-3bfab50b89da.png)
Any ideas?

**Comment by worldveil** [comment]
This seems like a `ffmpeg` installation issue. What operating system are you using?

Do let us know if you followed the [installation instructions](https://github.com/worldveil/dejavu/blob/master/INSTALLATION.md) but still have problems.

**Comment by halobalazs** [comment]
operation system: fedora lxde 20
and yes, i followed the instructions. the audio file is one of the sample mp3 file that came with dejavu

**Comment by halobalazs** [comment]
it works! :) an update fixed my problem
