### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by BeeZerk** [worldveil/dejavu#69]
Hey, maybe this is not an issue but i have a question about dejavu. How is it possible to use it with postgresql? I create a new database script and rewrite the sql statements. But since there is no hex or unhex function in postgresql it wont work. I use the encode/decode function but for example the decode function returns a longer string than the unhex in mysql. Is there any solution?

**Comment by worldveil** [comment]
@BeeZerk do you mean a database adapter? Would welcome a pgsql PR if you have one working.

**Comment by BeeZerk** [comment]
@worldveil yeah i have one now. But my python knowledge isnt that good so maybe there are some bugs. But i can create fingerprints from a directory and recognize files. If you want i send it to you

**Comment by avilaton** [comment]
The best way to do this would be to migrate the current adapter to sqlalchemy which is not very hard.
