### ISSUE TITLE
an unhandled win32 exception occurred in python.exe

### ISSUE THREAD

**Issue by pete111** [worldveil/dejavu#70]
Hi guys, 

when I run example.py error occures: an unhandled win32 exception occurred in python.exe

What is wrong?

**Comment by worldveil** [comment]
As stated here, Dejavu has only been tested on [Unix systems](https://github.com/worldveil/dejavu/blob/master/INSTALLATION.md).

It has to do with the use of the python multiprocessing library. If you'd like to dig in and fix you are welcome to submit a PR, but I have no plans to add Windows support.
