### ISSUE TITLE
Worked fine earlier but now fingerprinting failed in ubuntu studio 14

### ISSUE THREAD

**Issue by pragyankb** [worldveil/dejavu#73]
Failed fingerprinting
Traceback (most recent call last):
  File "/home/sp/Documents/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

**Comment by worldveil** [comment]
This is an `ffmpeg` issue, and I can't debug further except to say that the instructions for installation are [here](https://github.com/worldveil/dejavu/blob/master/INSTALLATION.md) and that you should write a specific issue if you have one with that process.
