### ISSUE TITLE
Decoding error with 32-bits files ? 

### ISSUE THREAD

**Issue by kursusHC** [worldveil/dejavu#80]
Decoding fails when submitting 32-bits files (.m4a in this case). 

It works perfectly for 16-bits files (s16p according to ffmpeg) but for 32-bits files (s32p according to ffmpeg) I get an error :

Decoding failed. ffmpeg returned error code: {0}".format(retcode)

I know pydub does not support 24-bits but I thought it was ok with 32-bits. 

I'm using latest version of Dejavu. 

Thank you.

Example file here : http://wikisend.com/download/406618/32bitsError.m4a

**Comment by thesunlover** [comment]
taking action on this issue

**Comment by thesunlover** [comment]
Well with the provided file there were no errors on my machine.
where do you get the decoding err?

**Comment by thesunlover** [comment]
would be even better to paste the whole traceback

**Comment by kursusHC** [comment]
Thanks for the answer. I was running ffmpeg 1 which triggered this error, problem solved with ffmpeg 2.

**Comment by thesunlover** [comment]
You're welcome.
