### ISSUE TITLE
Online Database

### ISSUE THREAD

**Issue by RomHartmann** [worldveil/dejavu#81]
Hi, this is not exactly an issue, but is there an online music database that one can link Dejavu to by just entering the correct JSON database config?

Thanks!

**Comment by worldveil** [comment]
There is no online music database, you plug into your own MySQL or (soon) PostgreSQL and record your own fingerprints. 

Dejavu is meant for recognizing all sorts of pre-recorded audio. Plus, each user's needs are different. Want more accurate fingerprinting at the expense of most fingerprints? Raise the DEFAULT_FAN_VALUE. Need higher collision guarantees but don't mind the extra storage cost? You can decrease the FINGERPRINT_REDUCTION and keep more characters of each SHA-1. 

Dejavu is meant to adapt to many different use cases which necessarily means that if you change fingerprinting parameters in this file your database will have differently distribution and structure.
