### ISSUE TITLE
How to reduce the size of the database?

### ISSUE THREAD

**Issue by eyalgaon84** [worldveil/dejavu#85]
Hi,
I need to index a lot of mp3 files, and then I take a 2 sec of some file to recognize, the 2 sec taken from the original file so it hasn't background noise ,
my question is how can I reduce the size of the database?
What can I change in the params on the fingerprint.py  file ?

Thanks,
Eyal

**Comment by winos** [comment]
i recommend you read this document: 

https://github.com/worldveil/dejavu#tuning

**Comment by worldveil** [comment]
@winos is correct. I hope that helps!
