### ISSUE TITLE
Error - trying to open display

### ISSUE THREAD

**Issue by aemerich** [worldveil/dejavu#88]
I'm getting this error:

> > > from dejavu import Dejavu
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "dejavu/**init**.py", line 3, in <module>
> > >     import fingerprint
> > >   File "dejavu/fingerprint.py", line 3, in <module>
> > >     import matplotlib.pyplot as plt
> > >   File "/usr/lib64/python2.6/site-packages/matplotlib/pyplot.py", line 78, in <module>
> > >     new_figure_manager, draw_if_interactive, show = pylab_setup()
> > >   File "/usr/lib64/python2.6/site-packages/matplotlib/backends/**init**.py", line 25, in pylab_setup
> > >     globals(),locals(),[backend_name])
> > >   File "/usr/lib64/python2.6/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
> > >     from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
> > >   File "/usr/lib64/python2.6/site-packages/matplotlib/backends/backend_gtk.py", line 8, in <module>
> > >     import gtk; gdk = gtk.gdk
> > >   File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/**init**.py", line 64, in <module>
> > >     _init()
> > >   File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
> > >     _gtk.init_check()
> > > RuntimeError: could not open display

Can anyone help me?

**Comment by thesunlover** [comment]
Hi, @aemerich 
did you use the proper version of Python?

**Comment by thesunlover** [comment]
most of the depencies require Python 2.7 / Python 3

**Comment by soruly** [comment]
Running without a GUI would result in such error.
You have to set matplotlib to use non-interactive backend.
Try modifying the first few lines of `fingerprint.py` fixes this for me
```
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
```
