### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by shemul** [worldveil/dejavu#95]
After installing all dependencies on Debian environment I got this ... any solution ?

```
`Fingerprinting channel 1/2 for music/The-Lights-Galaxia--While-She-Sleeps.mp3
Failed fingerprinting
Traceback (most recent call last):
  File "/home/djvu/dejavu/dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 653, in next
    raise value
MemoryError`
```

**Comment by thesunlover** [comment]
we already work on this issue #18

**Comment by ZeroCool940711** [comment]
This memory error seems to happen only on windows, I had this problem while trying to use dejavu on my Windows Desktop PC but when I ran it on my server using Ubuntu it didn't give any error about the memory, my Windows PC has 12Gb of RAM and a Intel Core i7 CPU and the server has only a dual core CPU and 4GB of RAM, so it is clear that my windows PC has more resources than my Ubuntu server.

**Comment by thesunlover** [comment]
@ZeroCool940711 
It's not only Windows:
https://github.com/worldveil/dejavu/issues/18#issue-25217561
in the first comment in the issue it clearly says:
ubuntu/5GB ram/3GB swap.

**Comment by shemul** [comment]
I was trying to on my virtual PC. Problem resolved on my linux :+1:
